In [1]:
#Exp no:4

In [2]:
#Aim : To perform Missing Value Treatment

In [3]:
# Name:Komal Sawarkar
# Roll no.:54
# Sec:C
# Subject:DSS
# Date:19/08/26

In [4]:
#importing the basic library
import pandas as pd

In [5]:
import os

In [6]:
os.getcwd()

'C:\\Users\\VICTUS'

In [7]:
os.chdir("C:\\Users\\VICTUS\\Downloads")

In [8]:
data=pd.read_csv('titanic.csv')

In [9]:
data.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [10]:
data.tail()

     PassengerId  Survived
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

In [11]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
dtypes: int64(2)
memory usage: 6.7 KB

In [12]:
data.describe()

       PassengerId    Survived
count   418.000000  418.000000
mean   1100.500000    0.363636
std     120.810458    0.481622
min     892.000000    0.000000
25%     996.250000    0.000000
50%    1100.500000    0.000000
75%    1204.750000    1.000000
max    1309.000000    1.000000

In [25]:
data.isna()

     PassengerId  Survived
0          False     False
1          False     False
2          False     False
3          False     False
4          False     False
..           ...       ...
413        False     False
414        False     False
415        False     False
416        False     False
417        False     False

[418 rows x 2 columns]

In [26]:
data.isna().any()

PassengerId    False
Survived       False
dtype: bool

In [29]:
df2=data["PassengerId"].fillna(29.6991180)

In [30]:
df2.isna().sum()

np.int64(0)

In [31]:
df3=data.dropna()

In [32]:
df3

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [33]:
data.isna().sum()

PassengerId    0
Survived       0
dtype: int64

In [35]:
df4=data["Survived"].dropna()

In [36]:
df4

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

In [37]:
df4.isna().sum()

np.int64(0)